# -*- coding: utf-8 -*-
"""Exercise 5 Compute the area of circle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCDcv1EDXuG3PyRINr0S3p4YOA6Bupmx
"""

# Area of circle
# input is information entered into a program, whether manually by the programmer or digitally
from math import pi
r = float(input("Input the radius of the circle: ")) # ask for a radius of circle
print("The area of the circle with radius " + str(r) + "is: " + str(pi * r**2))