# -*- coding: utf-8 -*-
"""Exercise 1 Print Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rhvriw9UOnfdWh1ZNkEGu5pmMpaKj34W
"""

# Print Strings
# Enter a Nursery Rhyme you want and print it
print('If youre happy and you know it clap your hands')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it clap your hands')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it do all three')
print('Hurray')
print('If youre happy and you know it do all three')
print('Hurray')
print('If youre happy and you know it and you really wants to show it')
print('If youre happy and you know it do all three')
print('Hurray')