# -*- coding: utf-8 -*-
"""Exercise 2 Print the Python version.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u7AalITOG5iigO1myIyJVOCdjccSp45Y
"""

# Print the version of python
#to know the latest version of python you're using
import sys #transferring information or preferences from one program to another
print("Python version") #to be specific with the 'version'
print(sys.version)

print("Version info.")  #specific with the infos in version
print(sys.version_info)

from platform import python_version
print(python_version())