# -*- coding: utf-8 -*-
"""Exercise 4 Strings Concatination.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7JsP6EWxypTvR9ShStPR6dwFC5T1rxB
"""

# Strings Concatination
#Write three strings in different variables and print the output as one string.
str = 'Hello World!' #str = strings is used for data values made consisting of character sequences in an orderly fashion
print(str)
print(str[0])
print(str[2:5])
print(str[2:])
print(str * 2)
print(str + "TEST")

#working with strings
sentence1= 'Today is 6th October, 2022, Thursday'
print(sentence1)
print(sentence1[0])
print(sentence1[0:5])
print(sentence1[4:])
print(sentence1*2)

sentence2= "Today is pur fifth session on 'introduction on Programming'"
print(sentence2)

sentence3= 'Today we are learning about different types of variables in python programming'
print(sentence3)

print(sentence1+sentence2+sentence3)