# -*- coding: utf-8 -*-
"""Exercise 5 Change Guest List.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eXRyY26Q_FQj15tEeTwuGDs8HY8In-q2
"""

#names of ladies 
name = ['Clare', 'Eurille', 'Louise']
name[0]='Carla'
print(name)

#asking Carla a question
name = ['Carla', 'Euille', 'Louise']
print("Can you do it on dinner time, " + name[0].title() + "?")