# -*- coding: utf-8 -*-
"""Exercise 2 Greetings.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-dQWx9jU_19xN9-baGMEoItOAM8YktH
"""

#greetings to the ladies named, Eurille and Louise
name = ['Eurille', 'Louise']
print("Hi ganda mo " + name[0].title() + "!")
print("Hey beautiful " + name[1].title() + "!")