# -*- coding: utf-8 -*-
"""Exercise 4 Guest List.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQ8g1mpYVqU5zrtySXrWdFjz4fJd7SG6
"""

#asking a lady out for dinner
name = ['Clare', 'Eurille', 'Louise']
print("Are you available for dinner, " + name[0].title() + "?")
print("Do you want some dinner, " + name[1].title() + "?")
print("Are you free for later's dinner, " + name[2].title() + "?")