# -*- coding: utf-8 -*-
"""Exercise 1 Names.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mD3Hz6ioXyzU4Wr-TtR4inW32pio6eMc
"""

#the name Eurille and Louise
name = ['Eurille', 'Louise']
print(name[0])
print(name[1])