# -*- coding: utf-8 -*-
"""Exercise 7 Seeing The World.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12LYezqLTNubz8HunUDBS1VuJIG5kNl0l
"""

#random countries and cities 
location = ['Philippines', 'Canada', 'Paris', 'Washington', 'United Kingdom']
print(location)
location.sort()
print(location)

#random countries and cities in a different order
location = ['Canada', 'Paris', 'Philippines', 'United Kingdom', 'Washington']
print(location)
location.reverse()
print(location)
location.reverse()
print(location)