# -*- coding: utf-8 -*-
"""Exercise 6 Shrinking Guest List.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rLPpFkHA0xLh8b2vsRXP7sGwwg2mi1II
"""

#the names Carla, Eurille and Louise
name = ['Carla', 'Eurille', 'Louise']
popped=name.pop()
print(name)
del name [0:3]