# -*- coding: utf-8 -*-
"""Exercise 3 Your Own List.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kcCteGztSmJMsQD63WhXsS_fHb3wrsN
"""

#dream cars of a person 
name = ['Ford', 'Civic', 'Honda']
print("I like to have a " + name[0].title())
print("I wish I have a " + name[1].title())
print("I like " + name[2].title())