# -*- coding: utf-8 -*-
"""Exercise 2 Glossary

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19D7YWO-0HUDM6hYtnWA0fGh9XZixE_qr
"""

glossary = {
    'concatenate': 'to join two strings or other applicable oject types together.',
    'for loops': 'for loops are used to perfrom some action on each item in a list.',
    'list': 'lists are used to store multiple objects together',
    'Python': 'interpreted object oriented, programming language',
    'Variables': 'symbolic name is a reference to an object'
}
print('concatenate :')
print(glossary['concatenate'] + '\n')
print('for loops :')
print(glossary['for loops'] + '\n')
print('list :')
print(glossary['list'] + '\n')
print('Python :')
print(glossary['Python'] + '\n')
print('Variables :')
print(glossary['Variables'])