# -*- coding: utf-8 -*-
"""Exercise 1 Person

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GLOo_JTomvKouRe5-LLDzEPLcdFefbO
"""

person={'first_name':'Marlvienne','last_name':'Ramos','age':'18','city':'Dubai'}
print(person)
print(person['first_name'])
print(person['last_name'])
print(person['age'])
print(person['city'])