# -*- coding: utf-8 -*-
"""Exercise 3 Glossary 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3SGNC-S2DJJs-95H2uEuR09hK6at7wA
"""

glossary = {
    'value': 'An inbuilt method in Python programming language that returns a view object.',
    'string': 'Arrays of bytes representing unicode characters.',
    'list': 'Created by placing elements inside square brackets, separated by commas. ',
    'key': 'Used to retrieve all of the keys from the dictionary. ',
    'loop': 'Repeating something over and over until a particular condition is satisfied.',
    'float': 'Important method that is useful to represent floating-point numbers.',
    'dictionary': 'Used to store data values in key:value pairs.',
    'conditional test': 'The if statement is a conditional statement in python, that is used to determine whether a block of code will be executed or not.',
    'boolean expression': 'Evaluates to one of two states true or false.',
    'comment': 'Identified with a hash symbol, #, and extend to the end of the line.',
    }

for word, definition in glossary.items():
    print("\n" + word.title() + ": " + definition)