# -*- coding: utf-8 -*-
"""Execise 4 Rivers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ccAZMIrdQEIGfEo00EbrhNCdFD9t94MB
"""

rivers = {'Egypt': 'Nile', 'Brazil': 'Amazon', 'Russia': 'Yenisei'}

for river, country in rivers.items():
    print("The " + river.title() + " flows through " + country.title() + ".")

print("\nThe following countries are included in this data set:")
for river in rivers.keys():
    print("- " + river.title())

print("\nThe following rivers are included in this data set:")
for country in rivers.values():
    print("- " + country.title())