# -*- coding: utf-8 -*-
"""Exercise 3 Infinity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfguBA_y91WbITyByEOFQnSFYHChx7QF
"""

# Define a variable
i = 5
# Run this loop while i is less than 15
while i < 15:
    # Print a message
    print("Good Morning!")