# -*- coding: utf-8 -*-
"""exercise 4 Deli

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y3jWUX5IVv-Dw8ptrTEmp1HoB2Sb3vFX
"""

sandwich_orders = ['shawarma', 'cheese', 'paratha', 'turkey'] #make a list for sandwich orders
finished_sandwiches = []

while sandwich_orders:
    current_sandwich = sandwich_orders.pop()
    print("I'm working on your " + current_sandwich + " sandwich.") #make a statement for like doing the sandwich
    finished_sandwiches.append(current_sandwich)

print("\n")
for sandwich in finished_sandwiches:
    print("I made a " + sandwich + " sandwich.") #list of finished orders