# -*- coding: utf-8 -*-
"""Exercise 1 Pizza Toppings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dk8lCUzg8QgWOUR8StexrgJXsdhyWKcZ
"""

prompt = "\nAny topping would you like on your pizza?"
prompt += "\nEnter 'quit' when you are finished: "

while True:
    topping = input(prompt)
    if topping != 'quit':
        print("  I'll add " + topping + " to your pizza.")
    else:
        break