# -*- coding: utf-8 -*-
"""Exercise 2 Movie Ticket

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roWg7xr_bNze6NnnUL0-kT7jxgxHgBxD
"""

prompt = "How old are you?"
prompt += "\nEnter 'quit' when you are finished. "

while True:
    age = input(prompt)
    if age == 'quit':
        break
    age = int(age)

    if age < 3:
        print("  You get in free!")
    elif age < 13:
        print("  Your ticket is Aed25.")
    else:
        print("  Your ticket is Aed35.")