# -*- coding: utf-8 -*-
"""Exercise 1 Message

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sEpnv0CBKULN7IbZLkZ9TKt0g8MVNjvW
"""

def display_message(): #write down what do you learned today
    "Display a message about what I'm learning."
    message = "I'm learning functions."
    print(message)

display_message()