# -*- coding: utf-8 -*-
"""Exercise 4 Large tshirts

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLUY4LXeY6M3l3I7sd-IQYKvEwotEb7T
"""

def make_shirt(size='large', message='I Python You!'):
    "Summarize the shirt that's going to be made."
    print("\nI'm going to make a " + size + " t-shirt.")
    print('It will say, "' + message + '"')

make_shirt()
make_shirt(size='small')
make_shirt('medium', 'Python!')