# -*- coding: utf-8 -*-
"""exercise 3 Tshirt

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CRLxosRo51kAyTK1uptcYM-11zOHYMiH
"""

def make_shirt(size, message): #enter a customize t-shirt you want
    "Summarize the shirt that's going to be made."
    print("\nI'm going to make a " + size + " t-shirt.")
    print('It will say, "' + message + '"')

make_shirt('extra large', 'I love Dancing!')
make_shirt(message="I adidas Dance", size='small')