# -*- coding: utf-8 -*-
"""Exercise 2 Favorite Book

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EK7mEDnIwcJxHKSQgkeKKrIy7TvoOuEm
"""

def favorite_book(title): #put a favorite book of yours
    "Display a message about someone's favorite book."
    print(title + " is my favorite book.")

favorite_book('Da Vinci Code')