# -*- coding: utf-8 -*-
"""Exercise 5 Cities

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FaioSzDnWVSqBEaAIgi17XKrA8RzQWJ
"""

def describe_city(city, country='Canada'):
    "Describe a city."
    msg = city.title() + " is in " + country.title() + "."
    print(msg)

describe_city('Toronto')
describe_city('Dubai', 'UAE')
describe_city('Vancouver')