# Print Strings
print('If youre happy and you know it clap your hands')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it clap your hands')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it stomp your feet')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it and you really want to show it')
print('If youre happy and you know it shout hurray (hurray)')
print('If youre happy and you know it do all three')
print('Hurray')
print('If youre happy and you know it do all three')
print('Hurray')
print('If youre happy and you know it and you really wants to show it')
print('If youre happy and you know it do all three')
print('Hurray')