# -*- coding: utf-8 -*-
"""Strings Concatination.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihzJNOrBm4TUDM6HevEQtCyReIAn45Su
"""

str = 'Hello World!'
print(str)
print(str[0])
print(str[2:5])
print(str[2:])
print(str * 2)
print(str + "TEST")

#working with strings
sentence1= 'Today is 6th October, 2022, Thursday'
print(sentence1)
print(sentence1[0])
print(sentence1[0:5])
print(sentence1[4:])
print(sentence1*2)

sentence2= "Today is pur fifth session on 'introduction on Programming'"
print(sentence2)

sentence3= 'Today we are learning about different types of variables in python programming'
print(sentence3)

#Strings Concatination
#Write three strings in different variables and print the output as one string.

print(sentence1+sentence2+sentence3)