# -*- coding: utf-8 -*-
"""Exercise 4 Favorite Number.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gy0t0Sp2dMjuMQy41OOiESKvVnnAg5x1
"""

#mathematical equations
#ask for 2 numbers
print('Enter 2 numbers: ')
x=int(input())
y=int(input())
print('The addition of '+str(x)+' and '+str(y)+' is '+str(x+y))
print('The subtraction of '+str(x)+' and '+str(y)+' is '+str(x-y))
print('The multiplication of '+str(x)+' and '+str(y)+' is '+str(x*y))
print('The division of '+str(x)+' and '+str(y)+' is '+str(x/y))
print('The modules of '+str(x)+' and '+str(y)+' is '+str(x%y))
print('The power of '+str(x)+' and '+str(y)+' is '+str(x**y))