# -*- coding: utf-8 -*-
"""Exercise 3 Stripping Names.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbkI3eDdljsgsxy9zqFNaTifcDqcis3u
"""

#the word hotdog
word='   Hotdog'
new_word=word.lstrip()
print(word)
print(new_word)

#the name Yen
word='Yen     '
new_word=word.rstrip()
print(word)
print(new_word)

#the name Clare
word='     Clare     '
new_word=word.strip()
print(word)
print(new_word)

#To add a tab to your text, use the character combination \t
print("She is\tUgly")
#to add a newline in a string, use the character combination \n
print("\n")
print("Programming Languages: \nPython\nC\nJava")
print("\n")
#fromatting using \t and \n
print("Programming Language:\n\tPython\n\tC\n\tJava")