# -*- coding: utf-8 -*-
"""Exercise 5 USB Shopper.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENB6Ol1Ei957KdJcp3yl76BVjvCfqV-B
"""

# Conversation of the girl buying USB sticks 
print('A girl goes to a shop to buy USB\nGirl: How much is the USB?\nShopper:$6\nGirl:Ill get USB Sticks for $50')
No_of_USB=50//6
money_back=50%6
print('The shopper gives the girl '+str(No_of_USB)+' USBs'+' and returns her '+str(money_back)+'$')
print('The shopper give the girl '+str(50//6)+' USBs'+' and returns her '+str(50%6)+'$')