# -*- coding: utf-8 -*-
"""Exercise 2 Variables.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvWIatk32A15r2s2NwtR26F77cbY-QIT
"""

#a quote by Aberhani
print('Aberjhani once said, "This fire that we call Loving is too strong for human minds. But just right for human souls."')