# -*- coding: utf-8 -*-
"""Exercise 1 Variables.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gFP4G6lPYnUnf7eZB7Lc9PRkXMbW5-oW
"""

#area of square
#ask for a number
print('Please enter the side of square:') 
side= int(input())
print('Side of the square=', side)
print('The area of a square with side '+str(side)+ 'units='+ str(side**2)+ 'sq units')

#area of circle
#ask for a number
PI=4.541
print('Enter the radius of a circle:')
r=int(input())
print('The area of the circle with radius '+str(r)+' units=: '+str(PI*r**2)+ 'sq units')