# -*- coding: utf-8 -*-
"""Exercise 1 Alien colors #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYwymBEFVYufPbCRX3h4PDW2mi6NUyDK
"""

alien_color = 'green'
print('Choose and alien color: ')
aline_color=str(input())
if alien_color is 'green':
  print('The player just earned 5 points')