# -*- coding: utf-8 -*-
"""Exercise 4 Stages of Life

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-zQFVFntXIPLBJ4fSZ7ZjmqZQqWPHPl
"""

age = 28
if age < 2:
    print("You're a baby!")
elif age < 4:
    print("You're a toddler!")
elif age < 13:
    print("You're a kid!")
elif age < 20:
    print("You're a teenager!")
elif age < 65:
    print("You're an adult!")
else:
    print("You're an elder!")