# -*- coding: utf-8 -*-
"""Exercise 3 Alien Color #3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gnSaUiC2n1XoOAW-RXdLn6VT6IWkK9y
"""

print('Choose an alien color: ')
alien_color=str(input())
if alien_color=='green' :
  print('the player just earned 5 points')
elif alien_color=='yellow' :
  print('The player earned 10 points')
else :
  print('The player just earned 15 points')