# -*- coding: utf-8 -*-
"""Exercise 5: USB Shopper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ys7WnBVQC03Pl5FPs0_Z2zm-Iu8TVUTm
"""

# Conversation of the girl buying USB sticks exer 5
print('A girl goes to a shop to buy USB\nGirl: How much is the USB?\nShopper:$6\nGirl:Ill get USB Sticks for $50')
No_of_USB=50//6
money_back=50%6
print('The shopper gives the girl '+str(No_of_USB)+' USBs'+' and returns her '+str(money_back)+'$')
print('The shopper give the girl '+str(50//6)+' USBs'+' and returns her '+str(50%6)+'$')