# -*- coding: utf-8 -*-
"""Exercise 1: Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DzsUnXquIehx_In_aVoau6GBe0UHGHUa
"""

print('Please enter the side of square:')
side= int(input())
print('Side of the square=', side)
print('The area of a square with side '+str(side)+ 'units='+ str(side**2)+ 'sq units')

PI=4.541
print('Enter the radius of a circle:')
r=int(input())
print('The area of the circle with radius '+str(r)+' units=: '+str(PI*r**2)+ 'sq units')