# -*- coding: utf-8 -*-
"""Exercise 2: Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3KNJhTxES4Xo8rdspkJg1K0MD6pXmUT
"""

print('Aberjhani once said, "This fire that we call Loving is too strong for human minds. But just right for human souls."')