# -*- coding: utf-8 -*-
"""Exercise 4: Favorite Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4vozq4Qc3oHqemJpJZ7pwB3kHEGNioQ
"""

print('Enter 2 numbers: ')
x=int(input())
y=int(input())
print('The addition of '+str(x)+' and '+str(y)+' is '+str(x+y))
print('The subtraction of '+str(x)+' and '+str(y)+' is '+str(x-y))
print('The multiplication of '+str(x)+' and '+str(y)+' is '+str(x*y))
print('The division of '+str(x)+' and '+str(y)+' is '+str(x/y))
print('The modules of '+str(x)+' and '+str(y)+' is '+str(x%y))
print('The power of '+str(x)+' and '+str(y)+' is '+str(x**y))