# -*- coding: utf-8 -*-
"""Exercise 5 Cities.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rSf8MKBiaMC5NW3rU5PKCglzJ0zaqTRa
"""

#describing random cities
def describe_city(city, country='Canada'):
    "Describe a city."
    msg = city.title() + " is in " + country.title() + "."
    print(msg)

describe_city('Toronto')
describe_city('Dubai', 'UAE')
describe_city('Vancouver')