# -*- coding: utf-8 -*-
"""Exercise 2 Favorite Book.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v24TEwxE6qxmfCuvzCkCjInsg_kxrTCa
"""

#displaying a message about a person's favorite book
def favorite_book(title): #put a favorite book of yours
    "Display a message about someone's favorite book."
    print(title + " is my favorite book.")

favorite_book('Da Vinci Code')