# -*- coding: utf-8 -*-
"""Exercise 1 Message.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pBSjxpdoUN5JmKVgWTqFru0qF_PoI4nA
"""

#displaying a message regarding what you learned today
def display_message(): #write down what do you learned today
    "Display a message about what I'm learning."
    message = "I'm learning functions."
    print(message)

display_message()