# -*- coding: utf-8 -*-
"""Exercise 3 Tshirt.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2gdZKbTgFXzr_OxBZ7aa2UBTYQvB9NT
"""

#making a customized shirt
def make_shirt(size, message): #enter a customize t-shirt you want
    "Summarize the shirt that's going to be made."
    print("\nI'm going to make a " + size + " t-shirt.")
    print('It will say, "' + message + '"')

make_shirt('extra large', 'I love Dancing!')
make_shirt(message="I adidas Dance", size='small')