# -*- coding: utf-8 -*-
"""Exercise 1 Alien Colors #1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q5npEirAk_7MVIikxKaHjRuHn4aPMd6w
"""

#green, the color of an alien
#ask for a color
alien_color = 'green'
print('Choose and alien color: ')
alien_color=str(input())
if alien_color is 'green':
  print('The player just earned 5 points')