# -*- coding: utf-8 -*-
"""Exercise 3 Alien Colors #3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbyCifw3_Wu5RGNgedBIhwbHR61_f0E1
"""

#alien colors
#ask for an alien color
print('Choose an alien color: ')
alien_color=str(input())
if alien_color=='green' :
  print('the player just earned 5 points')
elif alien_color=='yellow' :
  print('The player earned 10 points')
else :
  print('The player just earned 15 points')