# -*- coding: utf-8 -*-
"""Exercise 5 Favorite Fruit.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6UI4ZmdWbS2raY2bbFYYa5ApqzpF_8f
"""

#favorite fruits
#ask for a fruit
favorite_fruits = ['apricot','blueberries', 'bananas', 'peaches','apples']
print('What is your favorite fruit: ')
favorite_fruits=str(input())
if 'bananas' in favorite_fruits:
    print("You really like bananas!")
if 'apples' in favorite_fruits:
    print("You really like apples!")
if 'blueberries' in favorite_fruits:
    print("You really like blueberries!")
if 'apricots' in favorite_fruits:
    print("You really like apricots!")
if 'peaches' in favorite_fruits:
    print("You really like peaches!")