# -*- coding: utf-8 -*-
"""Exercise 3 Infinity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuSDG9pa5mev_5U78sUat3XgSfAV9dxk
"""

# Define a variable
i = 5
# Run this loop while i is less than 15
while i < 15:
    # Print a message
    print("Good Morning!")