# -*- coding: utf-8 -*-
"""Exercise 2 Movie Tickets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HJz8zB0CGS1IezgJF-BI7gH4CCzB0WNE
"""

#ask their age
prompt = "How old are you?" #prompt is whenever the function is invoked, a string will be displayed on the screen.
prompt += "\nEnter 'quit' when you are finished. "

while True:
    age = input(prompt)
    if age == 'quit':
        break
    age = int(age)

    if age < 3:
        print("  You get in free!")
    elif age < 13: #elif is short of is else
        print("  Your ticket is Aed25.")
    else:
        print("  Your ticket is Aed35.")