# -*- coding: utf-8 -*-
"""Exercise 5 Pets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yr0ZXXl2Y37NoIQd2smKltdrsXv6myqu
"""

# Make a list of empty spaces to put the animals.
pets = []

# Create unique pets and keep a list of each.
pet = {
    'animal type': 'Cat',
    'name': 'Rus',
    'owner': 'Yen',
    'weight': 26,
    'eats': 'rat',
}
pets.append(pet)

pet = {
    'animal type': 'Mice',
    'name': 'alvin',
    'owner': 'Clair',
    'weight': 2,
    'eats': 'corn',
}
pets.append(pet)

pet = {
    'animal type': 'Dog',
    'name': 'Kevin',
    'owner': 'Rile',
    'weight': 24,
    'eats': 'slippers',
}
pets.append(pet)

# Display details for each animal.
for pet in pets:
    print("\nHere's what I know about " + pet['name'].title() + ":")
    for key, value in pet.items():
        print("\t" + key + ": " + str(value))