# -*- coding: utf-8 -*-
"""Exercise 5 Change Guest List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6rhlKuwTB3tVF_k24uWJHkPuDoUHvGa
"""

name = ['Claire', 'Eurille', 'Louise']
name[0]='Carla'
print(name)

name = ['Carla', 'Euille', 'Louise']
print("Can you do it on dinner time, " + name[0].title() + "?")