# -*- coding: utf-8 -*-
"""Exercise 2 Greetings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgMluoF8ob7j0gdVATXs2CSbs0LcMQ86
"""

name = ['Eurille', 'Louise']
print("Hi ganda mo " + name[0].title() + "!")
print("Hey beautiful " + name[1].title() + "!")