# -*- coding: utf-8 -*-
"""Exercise 6 Shrinking Guest List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwUDYlQsm3HRpVKqrT5jXp_OjHWrkhch
"""

name = ['Carla', 'Eurille', 'Louise']
popped=name.pop()
print(name)
del name [0:3]