# -*- coding: utf-8 -*-
"""Exercise 7 Seeing The World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swshtIQOLpreiMxi411MZpa-Ils-pO0g
"""

location = ['Philippines', 'Canada', 'Paris', 'Washington', 'United Kingdom']
print(location)
location.sort()
print(location)

location = ['Canada', 'Paris', 'Philippines', 'United Kingdom', 'Washington']
print(location)
location.reverse()
print(location)
location.reverse()
print(location)