# -*- coding: utf-8 -*-
"""Exercise 1 Name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kV8O9oEEP1VWa87vRfqmQUvzx3EBMItm
"""

name = ['Eurille', 'Louise']
print(name[0])
print(name[1])