# -*- coding: utf-8 -*-
"""Exercise 3 Your own list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkvBca27QRiV_KcOQDbp-rh6bvDqWLVh
"""

name = ['Ford', 'Civic', 'Honda']
print("I like to have a " + name[0].title())
print("I wish I have a " + name[1].title())
print("I like " + name[2].title())